root: /
safe: false

name: 指间世界
theme: default
author: 湛之
email: i@wukezhan.com
url: http://www.wukezhan.com

paginate: 10
permalink: /:year-:month-:day/:title/

markdown: rdiscount
pygments: true

gaid: UA-16656304-1
disqusid: wukezhan
saying: 中原王气久消磨，四面军声逼楚歌。仗剑纵横驱虏骑，不教荆棘没铜驼！

